//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenificiaryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenificiaryMaster()
        {
            this.InstallmentDetails = new HashSet<InstallmentDetail>();
            this.Comments = new HashSet<Comment>();
            this.GeoTaggingDetails = new HashSet<GeoTaggingDetail>();
            this.InstallmentRejections = new HashSet<InstallmentRejection>();
        }
    
        public int BeneficiaryId { get; set; }
        public string BeneficairyName { get; set; }
        public string FatherName { get; set; }
        public string Mother { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public string PresentAddress { get; set; }
        public Nullable<int> DTRNo { get; set; }
        public Nullable<long> RecordNo { get; set; }
        public string Class { get; set; }
        public string General { get; set; }
        public string Single { get; set; }
        public string Disabled { get; set; }
        public string Password { get; set; }
        public Nullable<long> AdharNo { get; set; }
        public string VoterID { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> MojaNo { get; set; }
        public string KhataNo { get; set; }
        public Nullable<int> KhasraNo { get; set; }
        public string PlotNo { get; set; }
        public string PoliceStation { get; set; }
        public string WardNo { get; set; }
        public string District { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<long> AccountNo { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentDetail> InstallmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeoTaggingDetail> GeoTaggingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentRejection> InstallmentRejections { get; set; }
    }
}
