//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int BeneficiaryId { get; set; }
        public int InstallementId { get; set; }
        public string Reason { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual BenificiaryMaster BenificiaryMaster { get; set; }
        public virtual InstallmentDetail InstallmentDetail { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
