//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallmentDetail()
        {
            this.Comments = new HashSet<Comment>();
            this.GeoTaggingDetails = new HashSet<GeoTaggingDetail>();
            this.InstallmentSignings = new HashSet<InstallmentSigning>();
        }
    
        public int InstallmentId { get; set; }
        public int BeneficiaryId { get; set; }
        public Nullable<decimal> BeneficiaryAmnt { get; set; }
        public Nullable<decimal> LoanAmnt { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> Centre { get; set; }
        public string ConstructionLevel { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual BenificiaryMaster BenificiaryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeoTaggingDetail> GeoTaggingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentSigning> InstallmentSignings { get; set; }
    }
}
