//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentRejection
    {
        public int Id { get; set; }
        public int BeneficiaryId { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual BenificiaryMaster BenificiaryMaster { get; set; }
        public virtual InstallmentRejection InstallmentRejection1 { get; set; }
        public virtual InstallmentRejection InstallmentRejection2 { get; set; }
    }
}
